--- Makefile.am
+++ Makefile.am
@@ -30,7 +30,7 @@
 
 openca_prefix		= @openca_prefix@
 
-ACLOCAL_AMFLAGS		= -I m4
+ACLOCAL_AMFLAGS		= -I build
 
 AUTOMAKE_OPTIONS = no-dependencies
 SUBDIRS = src docs etc 
@@ -61,7 +61,7 @@
 MAINTAINERCLEANFILES = Makefile.in aclocal.m4 configure \
 	$(AUX_DIST)
 
-bin_SCRIPTS = \
+noinst_SCRIPTS = \
 	scripts/ocspd-genreq.sh \
 	test/test.sh
 
--- configure.in
+++ configure.in
@@ -5,7 +5,7 @@
 AC_INIT(src/ocspd/ocspd.c)
 AC_PREREQ( 2.50)
 AC_CONFIG_AUX_DIR(build)
-AC_CONFIG_MACRO_DIR([m4])
+AC_CONFIG_MACRO_DIR([build])
 VERSION=`cat VERSION`
 
 PACKAGE_NAME="openca-ocspd"
@@ -20,7 +20,7 @@
 AC_SUBST(PKG_MIN)
 
 mybits=""
-if [[ `uname -p` = "x86_64" ]] ; then
+if [[ `uname -m` = "x86_64" ]] ; then
 	mybits="64";
 fi
 AC_SUBST(mybits)
@@ -148,8 +148,8 @@
 AC_PROG_MAKE_SET
 AC_PROG_LN_S
 
-AM_PROG_LIBTOOL
-AC_SUBST(LIBTOOL_DEPS)
+dnl AM_PROG_LIBTOOL
+dnl AC_SUBST(LIBTOOL_DEPS)
 
 AC_SUBST(ac_aux_dir)
 
--- etc/Makefile.am
+++ etc/Makefile.am
@@ -5,12 +5,11 @@
 
 CHMOD = @CHMOD@
 
-EXTRA_DIST = ocspd.xml.in ocspd.in ca.d/*.xml
+EXTRA_DIST = ocspd.xml.in  ca.d/*.xml
 
 install-data-local:
 	@$(NORMAL_INSTALL)
 	$(mkinstalldirs) $(etc_prefix); \
-	$(mkinstalldirs) $(etc_prefix)/init.d; \
 	$(mkinstalldirs) $(etc_prefix)/ocspd; \
 	$(mkinstalldirs) $(etc_prefix)/ocspd/certs; \
 	$(mkinstalldirs) $(etc_prefix)/ocspd/private; \
@@ -24,18 +23,19 @@
 	      $(INSTALL_DATA) $$file $(etc_prefix)/ocspd; \
 	    fi \
 	  done ;
-	@ $(INSTALL_DATA) ocspd $(etc_prefix)/init.d/; \
-	$(CHMOD) +x $(etc_prefix)/init.d/ocspd ;
+	
 	@for file in token.d/*.xml ; do \
 	    if test -f $$file ; then \
 		$(INSTALL_DATA) $$file $(etc_prefix)/ocspd/pki/token.d ; \
 	    fi ; \
 	done ;
+	
 	@for file in hsm.d/*.xml ; do \
 	    if test -f $$file ; then \
 		$(INSTALL_DATA) $$file $(etc_prefix)/ocspd/pki/hsm.d ; \
 	    fi ; \
 	done ;
+	
 	@for file in ca.d/*.xml ; do \
 	    if test -f $$file ; then \
 		$(INSTALL_DATA) $$file $(etc_prefix)/ocspd/ca.d ; \
